### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by ivhazu** [gilliginsisland/hass-nissan-connect#2]
With both the stable version 1.0.3 and the pre-release 1.0.6 I receive an error message "Failed to connect" with my nissan connect userid and passoword (same userid and passowrd used also for MyNissan Europe).

**Comment by dragonjo84** [comment]
Me too

**Comment by gilliginsisland** [comment]
Sorry for the long delay on this. This only works for the Nissan Connect USA endpoint. I think there is another addon developed by someone else that works for EU endpoints. https://community.home-assistant.io/t/integration-for-nissanconnect-services/507695/149?page=2

**Comment by ivhazu** [comment]
Thanks for your answer.
